CREATE TABLE IF NOT EXISTS User(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    UUID VARCHAR(255) NOT NULL UNIQUE,
    Email VARCHAR(50) NOT NULL UNIQUE,
    Username VARCHAR(25) NOT NULL UNIQUE,
    Password VARCHAR(100),
    OAuthID VARCHAR(255) UNIQUE,
    Role TEXT NOT NULL CHECK (Role IN ('Admin', 'User', 'Moderator', 'DeleteUser')),
    IsLogged BOOL DEFAULT FALSE,
    IsDeleted BOOL DEFAULT FALSE,
    IsRequest BOOL DEFAULT FALSE,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Categories (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Name VARCHAR(50) UNIQUE
);

CREATE TABLE IF NOT EXISTS Posts (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    User_UUID VARCHAR(255) NOT NULL,
    Title TEXT NOT NULL,
    Category_ID INTEGER NOT NULL,
    Text TEXT,
    ImagePath TEXT,
    Like INTEGER,
    Dislike INTEGER,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (User_UUID) REFERENCES User(UUID),
    FOREIGN KEY (Category_ID) REFERENCES Categories(ID)
);

CREATE TABLE IF NOT EXISTS Post_Categories (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Post_ID INTEGER NOT NULL, 
    Categories_ID INTEGER NOT NULL,
    FOREIGN KEY(Post_ID) REFERENCES Posts(ID),
    FOREIGN KEY(Categories_ID) REFERENCES Categories(ID)
);

CREATE TABLE IF NOT EXISTS Comments (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    User_UUID VARCHAR(255) NOT NULL,
    Post_ID INTEGER NOT NULL,
    Text TEXT NOT NULL,
    Like INTEGER,
    Dislike INTEGER,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (Post_ID) REFERENCES Posts(ID) ON DELETE CASCADE,
    FOREIGN KEY (User_UUID) REFERENCES User(UUID)
);

CREATE TABLE IF NOT EXISTS Report (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    User_UUID VARCHAR(255) NOT NULL,
    Username VARCHAR(255) NOT NULL,
    Post_ID INTEGER NOT NULL,
    Title TEXT NOT NULL,
    Respons_Text TEXT,
    FOREIGN KEY (User_UUID) REFERENCES User(UUID)
);

CREATE TABLE IF NOT EXISTS Reaction (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Post_ID INTEGER,
    Comment_ID INTEGER,
    User_UUID VARCHAR(255) NOT NULL,
    Status VARCHAR(255) NOT NULL,
    FOREIGN KEY (Post_ID) REFERENCES Posts(ID) ON DELETE CASCADE,
    FOREIGN KEY (Comment_ID) REFERENCES Comments(ID) ON DELETE CASCADE,
    FOREIGN KEY (User_UUID) REFERENCES User(UUID),
    CHECK ((Post_ID IS NULL AND Comment_ID IS NOT NULL) OR (Post_ID IS NOT NULL AND Comment_ID IS NULL))
);

CREATE TABLE IF NOT EXISTS Notification (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    User_UUID VARCHAR(255) NOT NULL,
    Reaction_ID INTEGER,
    Post_ID INTEGER,
    Comment_ID INTEGER,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    IsRead BOOL,
    FOREIGN KEY (Comment_ID) REFERENCES Comments(ID),
    FOREIGN KEY (User_UUID) REFERENCES User(UUID),
    FOREIGN KEY (Reaction_ID) REFERENCES Reaction(ID),
    FOREIGN KEY (Post_ID) REFERENCES Posts(ID)
);

CREATE TABLE IF NOT EXISTS Image (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    FilePath TEXT,
    Post_ID INTEGER,
    FOREIGN KEY (Post_ID) REFERENCES Posts(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS oauth_states (
    state TEXT PRIMARY KEY,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
